language: node_js
node_js:
  - "11.15"
  - "12.3"
branches:
  only:
    - master
cache:
  directories:
    - node_modules

script:
  # Run test script
  - npm install
  # Run linting
  # - npm run lint
